### ISSUE TITLE
Implement the Edit Profile Page

### ISSUE THREAD

**Issue by mattpen** [phetsims/website-meteor#10]
Per design specification in https://drive.google.com/file/d/0B6CMwxdP0NGYOWZQc0NCOUxJTkk/view

**Comment by mattpen** [comment]
@oliver-phet - A couple of questions.

1.  On the design page there is a mockup of a confirmed/unconfirmed flag and an option to resend the confirmation email.  Currently the behavior if you are unconfirmed is that you receive a message that says invalid email/password and a prompt to resend the email at the sign-in prompt.  I would strongly recommend that we do not change this behavior and allow unconfirmed users to sign-in just to access this page.  Is it ok to remove these features?

2. Because the new edit profile page is built using the new React framework, this page will need to be mobile friendly.  On the design doc you provided a workup of the header using the reskinned design, but this header won't be published before the edit-profile page is.  How should we handle the side-navigation on mobile screens?

@amanda-phet suggested that we stack the navigation over the title over narrow screens.

Here's an example (live on https://ox-dev.colorado.edu/en/edit-profile):
![image](https://user-images.githubusercontent.com/11747676/32522835-1b18c93e-c3d6-11e7-94f2-6d47cc3db3c7.png)



Other possibilities include stacking it underneath the form or hiding it altogether.

**Comment by oliver-phet** [comment]
1. That's fine to remove the confirmed/unconfirmed. 
2. That sounds fine as long as all the content is available. Hopefully, the re-skinned header will come soon!
3. I hadn't planned on that behavior changing. Couldn't we use the existing design?
![image](https://user-images.githubusercontent.com/5090275/32531364-91380114-c400-11e7-8f96-5783c027d4cf.png)

**Comment by mattpen** [comment]
> Couldn't we use the existing design?

@oliver-phet - I don't see that in the mockup anywhere, but that sounds fine.  This is what I see:

![image](https://user-images.githubusercontent.com/11747676/32533825-da27b6f8-c40f-11e7-90a8-3018537665d5.png)

Am I missing an update?

**Comment by mattpen** [comment]
Implementation is finished
