### ISSUE TITLE
URL grows in length

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#12]
Goig back and forth between "Already Registered?" and "Register" continues to append `en%2Fsign-in%3Fdest%3D%2F` to the URL. You can get monster URLs like:

https://ox-dev.colorado.edu/en/register?dest=%2Fen%2Fsign-in%3Fdest%3D%2Fen%2Fsign-in%3Fdest%3D%2Fen%2Fsign-in%3Fdest%3D%2Fen%2Fsign-in%3Fdest%3D%2Fen%2Fsign-in%3Fdest%3D%2F

For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
This has been corrected.
