### ISSUE TITLE
Space needed between name and location of school

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#13]
Could use a space between a school's/organization's name and location:

<img width="612" alt="screen shot 2017-11-14 at 12 21 30 pm" src="https://user-images.githubusercontent.com/5863899/32800225-fb4a1886-c936-11e7-8f81-84e58df75aec.png">

For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
This has been fixed
