### ISSUE TITLE
"Other" text field

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#15]
All "Other" options need a text field so the user can specify the other. We also need to verify there is text in there before they can proceed with registration.

For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
All checkbox arrays should now have an other text field that is (a) only visible when other is selected, (b) highlighted in red when blank, and (c) does not allow progress when blank.

**Comment by mattpen** [comment]
The backend is not working, the other text fields are not being saved.

**Comment by phet-steele** [comment]
@mattpen only one out of the many Other fields say, "Other (Please Specify)".  Can you make that consistent while working on this issue? (not sure which way we want it, with the extra words or not)

**Comment by mattpen** [comment]
@phet-steele - I was following the design document, it has both versions.

@oliver-phet - Which version do you prefer, "Other" or "Other (Please Specify)" or the current mixture of both in the AI file?

**Comment by phet-steele** [comment]
> @oliver-phet - Which version do you prefer, "Other" or "Other (Please Specify)" or the current mixture of both in the AI file?

My 2 cents, "(Please Specify)" is unnecessary due to the implication of the sudden appearance of the text field, compounded by the error message if the field is left empty.

**Comment by oliver-phet** [comment]
I agree. "Other" seems cleaner and would prefer all to behave the same.

**Comment by mattpen** [comment]
All "Other" fields now use the same text.  However, registration is still not saving the value.

**Comment by mattpen** [comment]
@phet-steele the other field should be correct now, both in terms of the label and saving the user's value.  Please check and confirm.

**Comment by phet-steele** [comment]
@mattpen looks good as of now.
