### ISSUE TITLE
"Add you school" button when adding organization instead

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#16]
This button still says "Add your school" when I am adding an organization:

<img width="658" alt="screen shot 2017-11-14 at 12 42 04 pm" src="https://user-images.githubusercontent.com/5863899/32801116-5d31ff4e-c939-11e7-97ee-797153c190c7.png">

For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
This has been fixed
