### ISSUE TITLE
Missing "error" class

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#17]
The organization name and school name fields are lacking the "error" class, so they do not turn red when reporting an error:

<img width="622" alt="screen shot 2017-11-14 at 12 46 24 pm" src="https://user-images.githubusercontent.com/5863899/32801410-315b3826-c93a-11e7-8899-0ea64ab7275f.png">

For phetsims/QA#70.

**Comment by mattpen** [comment]
This has been fixed.
