### ISSUE TITLE
Missing string for "Register" button

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#18]
When signing up as a student, I'm missing the string for this button:

<img width="745" alt="screen shot 2017-11-14 at 1 09 19 pm" src="https://user-images.githubusercontent.com/5863899/32802421-3483db18-c93d-11e7-84b8-62e4e8506408.png">

Usually it should be "Next", but this is the last panel for students so it should say "Register".

For phetsims/QA#70.

**Comment by mattpen** [comment]
This has been fixed
