### ISSUE TITLE
Editing your profile to have no types is not validated before an update.

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#20]
1. Edit your profile
2. Uncheck every type in "I am a..."
3. Click "Update"

Not having any selected types is not handled on the edit page, and instead throws an internal error. Here is the console log:

<img width="975" alt="screen shot 2017-11-14 at 1 22 34 pm" src="https://user-images.githubusercontent.com/5863899/32802938-1dfef060-c93f-11e7-8620-b681a5912e5e.png">

For phetsims/QA#70.

**Comment by mattpen** [comment]
This has been fixed.
