### ISSUE TITLE
Error while attempting to delete your account

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#23]
<img width="464" alt="screen shot 2017-11-29 at 10 56 54 am" src="https://user-images.githubusercontent.com/5863899/33390741-1551cabc-d4f4-11e7-8295-12b976cb862f.png">

When deleting an account from the edit profile page.

Seen on macOS 10.13.1 FFQ. For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
The delete is working now, but does not invalidate the current session, so it looks like you are still logged in and you can access the edit profile page.

**Comment by mattpen** [comment]
OK, session is now invalidated after delete.  Once you hit the button the user is gone completely.

@phet-steele - please test and confirm.

**Comment by phet-steele** [comment]
Looks to work!
