### ISSUE TITLE
Can't edit email or change password

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#24]
<img width="471" alt="screen shot 2017-11-29 at 11 00 39 am" src="https://user-images.githubusercontent.com/5863899/33390963-bb96ef4c-d4f4-11e7-8dff-235d22c8843a.png">

Happens for both "Edit" (email) and "Change Password" (both of which don't look like links, by the way)

Seen on macOS 10.13.1 FFQ. For phetsims/QA#70.

**Comment by mattpen** [comment]
This should be fixed now, @phet-steele please confirm.

**Comment by phet-steele** [comment]
The password change works great, and the email change does change my email. However, changing my email does not sign me out (or at least it does not update the email in use for the current session). Isn't this a known issue? It leads to errors when trying to update your profile a second time.

**Comment by mattpen** [comment]
> Isn't this a known issue? It leads to errors when trying to update your profile a second time.

@phet-steele - I was not aware of this problem, is there an open issue?  There may be another way to solve the problem.  Do you know how to recreate this error?

**Comment by phet-steele** [comment]
> I was not aware of this problem, is there an open issue?

I thought maybe there was but couldn't find it.

> Do you know how to recreate this error?

Change your email, then in the same tab (verify the header still is using the old email) go to edit your profile and click update.

**Comment by mattpen** [comment]
@phet-steele - Submitting a change email request now signs you out.  If you try to sign in with the new email address, it asks you to resend the confirmation email.  If you sign in with the old address, it works just fine.  Does this sound like a reasonable workflow?

Slightly annoying if you want to change your email but don't actually want to go through the confirmation process, but it should be error free.

**Comment by phet-steele** [comment]
This works well in single-session use cases. However, in cases where a user has different sessions (one normal window, one private window) and uses one to confirm the email change, the other session remains signed in. Trying to "Update" your profile with the still signed in session will throw a null pointer exception and hang on the profile page. The user is not brought to the "Internal Error Occurred" page. That would probably be a better UX.

**Comment by mattpen** [comment]
@phet-steele - The error page should be implemented now.  Please test and confirm.  

Unfortunately graceful handling multiple sessions for a single user in the version of wicket we are using is not possible at this time.

**Comment by phet-steele** [comment]
@mattpen I don't get redirected to the error page when following the steps in https://github.com/phetsims/website-meteor/issues/24#issuecomment-351548347. I get the same error as shown in https://github.com/phetsims/website-meteor/issues/33

**Comment by mattpen** [comment]
@phet-steele - I don't have enough information to recreate this problem.  Can you please outline the steps?

**Comment by phet-steele** [comment]
1. Edit your profile with Session A. Change your email.
2. Don't click on the sent conformation link yet.
3. With Session A, log back in (using the old email) and go to edit your profile.
4. With Session B, click the confirmation link.
5. With Session A, click "Update Profile". Throws an error and it would be nice to be brought to the error page.

**Comment by mattpen** [comment]
@phet-steele - This should be fixed now, please check and confirm.

**Comment by phet-steele** [comment]
Woohoo thanks!
