### ISSUE TITLE
Sent to /header after updating your profile

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#25]
If you hit "Edit Profile" while already editing your profile, your URL becomes this:
https://ox-dev.colorado.edu/en/edit-profile?dest=%2Fen%2Fheader

And your destination after updating your profile becomes:
https://ox-dev.colorado.edu/en/header

Seen on macOS 10.13.1 FFQ. For phetsims/QA#70.

**Comment by mattpen** [comment]
@phet-steele this should be fixed, please confirm.

**Comment by phet-steele** [comment]
Looks good.
