### ISSUE TITLE
Lack of error message on Account Type panel

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#26]
The error message on the Account Type panel is a little sparse...

<img width="270" alt="screen shot 2017-11-29 at 11 13 15 am" src="https://user-images.githubusercontent.com/5863899/33391500-7b67f64e-d4f6-11e7-82ac-e05fce2db8a6.png">

Seen on macOS 10.13.1 FFQ. For phetsims/QA#70.

**Comment by mattpen** [comment]
@phet-steele this should be fixed, please confirm.

**Comment by phet-steele** [comment]
@mattpen almost, it doesn't work if what I choose is "Other" and do not specify:

<img width="274" alt="screen shot 2017-12-04 at 11 35 58 am" src="https://user-images.githubusercontent.com/5863899/33569598-64e8b300-d8e7-11e7-80a4-97cc3a24f2ff.png">

Not checking anything gives the correct error message, hence "almost".

**Comment by mattpen** [comment]
Fixed this case, back to you @phet-steele

**Comment by phet-steele** [comment]
Fixed! Thanks.
