### ISSUE TITLE
No visible "Next" and "Previous" buttons

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#27]
<img width="294" alt="screen shot 2017-11-29 at 11 29 07 am" src="https://user-images.githubusercontent.com/5863899/33392206-9643197e-d4f8-11e7-89b6-a2f0e44d8b27.png">

On https://ox-dev.colorado.edu/admin/schools and https://ox-dev.colorado.edu/admin/organizations. The buttons still work though!!

Seen on macOS 10.13.1 FFQ and Chrome. For phetsims/QA#70.

**Comment by phet-steele** [comment]
@mattpen pointed out this is because the buttons are missing a "background-color" attribute.

**Comment by mattpen** [comment]
@phet-steele - this should be fixed, please confirm.

**Comment by phet-steele** [comment]
Looks good, thanks @mattpen.
