### ISSUE TITLE
Other is required when unchecked

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#30]
Anywhere an "Other" field is used exhibits this problem. I'll use the Account Type page as an example.

1. Check "Other", but do not fill it in.
2. Click "Next". This will prompt the user with an error and trigger the bug.
3. Uncheck "Other" and check anything else.
4. Press "Next". You will still not be able to continue. Even though "Other" is unchecked, the user is still required to fill it in after the trigger in step 2.

For phetsims/QA#70.

**Comment by mattpen** [comment]
@phet-steele - This should be corrected. Please test and confirm.

**Comment by phet-steele** [comment]
Fixed.
