### ISSUE TITLE
"Teacher Educator/Coach" confused for "Teacher"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#32]
Signing up as a "Teacher Educator/Coach" during registration will mark you down as a "Teacher". Evident when going to edit your profile after registration.

For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
@phet-steele - This should be fixed now. Please test and confirm.

**Comment by phet-steele** [comment]
Looks fixed.
