### ISSUE TITLE
Can't save a custom school/organization

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#33]
Attempting to register with a custom school/organization throws an error:

`SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse`

result.content is a massive HTML form at this point.

The registration will still be successful, but your profile will not display your school/organization (it will be blank)

For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
@phet-steele - This should be fixed now.  Please test and confirm.

**Comment by phet-steele** [comment]
I was able to successfully register with a custom entry.

**Comment by phet-steele** [comment]
> I was able to successfully register with a custom entry.

HOWEVER! Creating a custom organization after registration (so during "Edit Profile") will not save the entry in my profile. I also don't get errors.

Creating and saving schools works fine in Edit Profile.

**Comment by mattpen** [comment]
@phet-steele - this should be working now.  I was able to save schools and organizations on both pages without error many times.  Please check and confirm.

**Comment by phet-steele** [comment]
Working, thanks!
