### ISSUE TITLE
School error message is incorrect

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#34]
Current error message when leaving your school empty:

<img width="615" alt="screen shot 2017-12-21 at 10 26 42 am" src="https://user-images.githubusercontent.com/5863899/34267291-8a745174-e639-11e7-98b4-3674ecdbf53c.png">

Seen on macOS 10.13.2 Chrome. For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
@phet-steele - This should be corrected, please test and confirm.

**Comment by phet-steele** [comment]
Good to go
