### ISSUE TITLE
Gen Ed teacher checkbox area is larger than necessary

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#35]
Users are able to select "General Education teacher" by clicking anywhere in its "section" (that isn't otherwise a different checkbox element).

So:

- Anywhere to the right of the selections
- In-between the checkboxes, and just below the "Other" checkbox

![webreg01](https://user-images.githubusercontent.com/5863899/34267610-c3fe0ce0-e63a-11e7-9d0a-c29189141658.gif)

Seen on macOS 10.13.2 Chrome. For phetsims/QA#70.

**Comment by mattpen** [comment]
@phet-steele - Nice gif!  This should be corrected, please test and confirm.

**Comment by phet-steele** [comment]
Fixed for me
