### ISSUE TITLE
Error formatting on edit profile page

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#37]
These error messages could be on a new line, or at least have white space separating them from their title. "Country" might have this issue too, but I can't have "Select your country" chosen to get an error.

<img width="632" alt="screen shot 2018-01-04 at 12 54 52 pm" src="https://user-images.githubusercontent.com/5863899/34581803-fc99ff40-f14e-11e7-972b-5ba64c2b9c1d.png">

For phetsims/QA#70.

**Comment by mattpen** [comment]
@phet-steele - These errors should now be on a new line.  Please check and confirm.

**Comment by phet-steele** [comment]
They are indeed. Thanks.
