### ISSUE TITLE
Fixes to admin school/organization db

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#39]
1. Edit School/Organization: if the admin clicks cancel to the edit dialog, do not update the entry (and don't display updated dialog).
2. Replace School/Organization: currently the dialog to replace a school is confusing:
![image](https://user-images.githubusercontent.com/5090275/35060447-ad856480-fb7b-11e7-9719-9deea5f13f34.png)

- @phet-steele and I tried to use this, but could not functionally replace a school using another ID.

The desired behavior is, click Replace icon. Enter the ID of the School/Org that the entry will be replaced with. 

3. Remove the "n/a" text on the replace dialog. Replace with "ID:" [id field]
4. Replace all "School"s strings with "Organization"s strings on the Organization admin page. Enumerated:
- Page title
- Include replaced "schools"
![image](https://user-images.githubusercontent.com/5090275/35062257-da660752-fb80-11e7-93a2-3c1082d0d46b.png)

- Button "All schools needing validation"
![image](https://user-images.githubusercontent.com/5090275/35062237-c6ea0516-fb80-11e7-8629-151dfd026bb1.png)
- Replace school dialog
![image](https://user-images.githubusercontent.com/5090275/35062220-ba0e2570-fb80-11e7-8021-dc4496e8e9ff.png)
- Edit school dialog
![image](https://user-images.githubusercontent.com/5090275/35062211-b143a3a2-fb80-11e7-8a60-6d8ed4097274.png)
- School updated/validated confirmation dialog
![image](https://user-images.githubusercontent.com/5090275/35062203-aa466e40-fb80-11e7-9d12-b4194b4df9e1.png)

5. Remove "Include NCES schools" on the Organization admin page
 

For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
@oliver-phet - I've fixed #1.

@phet-steele - Can you please confirm?  Also please check to see that the Add Sch/Org dialog on the reg and edit pages was not affected.

**Comment by mattpen** [comment]
I've also fixed # 4

**Comment by mattpen** [comment]
@oliver-phet @phet-steele - Fixes for all of the above requests should be complete now.  Please test and confirm.

**Comment by phet-steele** [comment]
@mattpen I'm having the same issue as the second bullet in https://github.com/phetsims/website-meteor/issues/40#issuecomment-358755645 when attempting to edit a school/org.

> I can't actually [edit] when hiding the state selection. The page gives me the "Please select a state or province" error message even though I shouldn't be required to have that entry.

**Comment by mattpen** [comment]
@phet-steele - This should be fixed now.  Please confirm.

**Comment by phet-steele** [comment]
@mattpen I can successfully get through the Edit panel without errors, but it doesn't seem to actually be updating. I waited ~1 hour after my edit and did not see the entry update.

**Comment by phet-steele** [comment]
@mattpen this is working now, thanks.
