### ISSUE TITLE
Fixes to State selection during registration

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#40]
Recommendations from @oliver-phet:

1. During registration and profile editing, if the user selects a country that has no state option (ie Vatican, Afghanistan, etc.), hide the "State - Select your state" option entirely, instead of making them choose a blank entry. (This is similar to how Zip Code is handled for non-US users)
2. During registration and profile editing, the "State" section should be written as "State/Province - select your state/province"

For phetsims/QA/issues/70.

**Comment by mattpen** [comment]
> During registration and profile editing, the "State" section should be written as "State/Province - select your state/province"

@phet-steele @oliver-phet - this doesn't fit in the space for a field header.  Is it ok to use "State/Province" as the header and "Select your state/province" as the initial default option in the dropdown list?

(This behavior is up now on ox-dev)

**Comment by phet-steele** [comment]
> @phet-steele @oliver-phet - this doesn't fit in the space for a field header. Is it ok to use "State/Province" as the header and "Select your state/province" as the initial default option in the dropdown list?

That's what I meant! So you did the right thing, will check shortly.

**Comment by phet-steele** [comment]
For (1), there are two problems.

-The Register Now button is now placed awkwardly when not showing the state selection  (usually it is bottom right):

<img width="804" alt="screen shot 2018-01-18 at 12 24 11 pm" src="https://user-images.githubusercontent.com/5863899/35117085-b6fe68ac-fc4a-11e7-85a0-de0f32b1ade5.png">

- I can't actually continue to register/update when hiding the state selection. The page gives me the "Please select a state or province" error message even though I shouldn't be required to have that entry.

**Comment by mattpen** [comment]
@phet-steele - These issues should be fixed now.  Please test and confirm.

**Comment by phet-steele** [comment]
@mattpen just found another place where (1) is not happening! When creating a custom school/organization, the selection will not hide.

**Comment by mattpen** [comment]
@phet-steele this should be fixed now, please confirm.

**Comment by phet-steele** [comment]
Looks good for now, thanks.
