### ISSUE TITLE
Remove commas from search string

### ISSUE THREAD

**Issue by mattpen** [phetsims/website-meteor#42]

**Comment by mattpen** [comment]
@phet-steele - searches with commas seems to be working as expected now.  Please test and confirm.

**Comment by mattpen** [comment]
@phet-steele - I forgot javascript's native string replace only replaces the first instance by default.  Commas anywhere is going to be problematic, so I'll update it.

**Comment by mattpen** [comment]
@phet-steele this should be fixed now.  Please confirm.

**Comment by phet-steele** [comment]
Working.
