### ISSUE TITLE
Admin page -- tweaks to 'Replace school' behavior

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#47]
1. The dialog to replace a school with another ID is pre-populated with the last ID pasted in. It would be better if this appeared blank initially to minimize replacing with the wrong school.
2. After clicking 'Replace School' on the "Are you sure you want to replace ... with ...?" dialog, remove the second, 'school updated' dialog.

**Comment by mattpen** [comment]
@oliver-phet - I've deployed fixes for these to ox-dev.  Can you please take a look and let me know if its ok to deploy?

**Comment by oliver-phet** [comment]
Yep, looks good. Ready to deploy.

**Comment by mattpen** [comment]
These have been deployed, closing.
