### ISSUE TITLE
Add school/organization. No matches in search

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#48]
KP wrote:
> One thing I noticed when I was using my 2nd parent account, was that since it wasn't prepopulated with organizations, I could type my organization in and think it should be OK, but then when I left that field it would return to blank and could go un-noticed. It might have been clearer that I should definitely be looking for a match, if the selection of matches popup thing was always there and said "No matches found" if nothing matched?

Here's a quick mockup of this.
![image](https://user-images.githubusercontent.com/5090275/35453324-00d5eff8-0287-11e8-8bcb-e4ea7e288572.png)

**Comment by mattpen** [comment]
@oliver-phet @kathy-phet - I thought that we had discussed this before and decided not to show it because it would prematurely encourage people to use the add dialog rather than the prepopulated schools.  

Should we add some constraint before it shows up?  For example the user needs to type at least 3 words or 15 characters before the prompt shows up?

**Comment by oliver-phet** [comment]
Maybe we put this on hold until we send out update emails and the database is more populated? I think a feature like this is a better user experience, but likely would increase the number of manual entries.

**Comment by mattpen** [comment]
> Maybe we put this on hold until we send out update emails and the database is more populated?

I thought we were adding this because the organization database isn't very well populated?

Maybe we could add this for organizations only?

**Comment by oliver-phet** [comment]
Ah right, sorry. I was considering the school side. I'd be fine with adding to org only.

**Comment by mattpen** [comment]
@oliver-phet - This should be available now for organizations on ox-dev.

**Comment by oliver-phet** [comment]
This looks good, @mattpen but I can't actually find anything using the search right now (even entries that are included in the ox-dev org database:
![image](https://user-images.githubusercontent.com/5090275/35933388-c0bbdf3e-0bf7-11e8-9f97-1f85302c97ba.png)
![image](https://user-images.githubusercontent.com/5090275/35933400-c9ebb372-0bf7-11e8-956b-3148814e0418.png)

**Comment by mattpen** [comment]
@oliver-phet - This is related to the improvements I've been working on for https://github.com/phetsims/website-meteor/issues/50.  They haven't been propogated over to organizations yet.

**Comment by mattpen** [comment]
@oliver-phet - It should be working now

**Comment by phet-steele** [comment]
This works for me.

**Comment by mattpen** [comment]
@oliver-phet - Anything else to do here? Is it ok to close/deploy?

**Comment by oliver-phet** [comment]
Looks good to deploy for orgs!

**Comment by mattpen** [comment]
This was deployed and appears to be working.
