### ISSUE TITLE
Add school/organization URL to registration

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#49]
Add an option for users to enter a link to their school/organization website. This would assist when trying to track down the legitimate entry.

[School]/[Organization] based on registration type.

Registration / desktop:
![image](https://user-images.githubusercontent.com/5090275/35457481-522b6504-0296-11e8-8971-6f36239ee47a.png)
Registration/mobile:
![image](https://user-images.githubusercontent.com/5090275/35457497-5ca06a84-0296-11e8-841d-b0027623779a.png)

**Comment by oliver-phet** [comment]
Also, not sure if the text should be?
- [School] web URL
- [School] website
- [School] web address

**Comment by mattpen** [comment]
@oliver-phet - What about `[School/Organization] website (optional)` for the field label and then in the field itself add a hint that says `https://www.example.com`?

![image](https://user-images.githubusercontent.com/11747676/35521091-1e2fbc54-04d6-11e8-8a8e-1db754a44a9b.png)

**Comment by oliver-phet** [comment]
Yep, that should work well. And this URL won't show up anywhere else on the site other than manually adding a school/org (but we'll want to see the url in the admin school/org table).

**Comment by kathy-phet** [comment]
Can the text say "(optional, but very helpful)"?

**Comment by oliver-phet** [comment]
@mattpen Can you start on adding the URL to added schools? I just chatted with KP.

**Comment by mattpen** [comment]
@oliver-phet - URLs should now be available to add to accounts and view on the admin pages on ox-dev. Can you take a look and let me know if you have any feedback?

**Comment by oliver-phet** [comment]
Is it possible to make the url clickable (open in new tab)? I can copy/paste the contents, but if we're going to be doing this hundreds of times, that could save some time.

**Comment by mattpen** [comment]
@oliver-phet - I've changed the urls to links on the admin page on ox-dev.  Does this look ok now?

**Comment by oliver-phet** [comment]
Looks good, thanks.

**Comment by phet-steele** [comment]
Works for moi.
