### ISSUE TITLE
Display profile email when editing as admin

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#53]
When editing a user's profile through the admin interface, can we put the email for the account we somewhere on the page? Just so that we know who we are editing? Just a small thing that would really only improve the admin user experience.

Something like:
<img width="665" alt="screen shot 2018-02-15 at 1 36 59 pm" src="https://user-images.githubusercontent.com/5863899/36279933-f2a5604c-1255-11e8-8d9e-6f89e8183b98.png">

Thoughts?

**Comment by oliver-phet** [comment]
This is probably a good idea. I don't go through huge batches of edits, but it seems like this could reduce the chance of accidentally editing the wrong user.

**Comment by mattpen** [comment]
It should already be on the Account Info tab, but it wouldn't be hard to add it here as well

**Comment by phet-steele** [comment]
> It should already be on the Account Info tab

It's nowhere to be seen when using this utility.

**Comment by phet-steele** [comment]
The change looks fine to me!

**Comment by mattpen** [comment]
OK, this will be deployed to production with the other changes for phetsims/website#672
