### ISSUE TITLE
Increase % of people adding their URL

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/website-meteor#56]
Oliver and I looked at the number of people adding their URL, and it seems like not many are. So I am hoping to come up with a solution to increase the % who add a URL when they add a company/school. 

Can we have this as a required field? And if they don't enter one, add the text that says, something like "Required field. If no "School website" / "Organization website" is available, please enter "None".  Or something like this to force / encourage more use of this option?

**Comment by mattpen** [comment]
Yes, we can make this required.  I'll start working on this today.

**Comment by mattpen** [comment]
URL is now required on ox-dev.  This will be deployed to production along with the changes for #55.

**Comment by phet-steele** [comment]
Only issue I see so far is that it is still labeled as optional:

<img width="300" alt="screen shot 2018-02-27 at 10 26 09 am" src="https://user-images.githubusercontent.com/5863899/36743935-c1d200ea-1ba8-11e8-908b-117973ecbc9d.png">

**Comment by mattpen** [comment]
That string has been corrected.

**Comment by mattpen** [comment]
This change was deployed tonight.
