### ISSUE TITLE
Gather statistics on success rates for selecting existing schools/orgs

### ISSUE THREAD

**Issue by mattpen** [phetsims/website-meteor#57]
#55 states: 
> We should gather better statistics on the success rates of people adding schools using existing entries.

I'm breaking this out into a separate issue.

To start with, since the exact duplicate checking was added last Thursday, it has caught 46 attempts.

Tagging @oliver-phet as FYI for now.

**Comment by mattpen** [comment]
@oliver-phet - Here is a chart showing the number of schools added and the number of user edits and registrations per day.  Will this be helpful? What other data points do you need?

![image](https://user-images.githubusercontent.com/11747676/36818027-89bf6ea6-1ca0-11e8-9e12-0e05eb543f8c.png)

**Comment by oliver-phet** [comment]
I'm not sure if that chart captures this, but I'd like to know what % of new US registrations/profile edits "found" a school in our database vs % of new US registrations/profile edits manually added a school.

**Comment by mattpen** [comment]
We need to add a filter so this is just US users and schools.

**Comment by mattpen** [comment]
@oliver-phet - here is the raw data for only US users and schools:

Date,Schools Added,Users Added or Edited
2018-1-26,49,89,0.550561797752809
2018-1-27,15,223,0.06726457399103139
2018-1-28,33,407,0.08108108108108109
2018-1-29,51,412,0.12378640776699029
2018-1-30,61,408,0.14950980392156862
2018-1-31,63,378,0.16666666666666666
2018-2-1,52,239,0.2175732217573222
2018-2-2,35,90,0.3888888888888889
2018-2-3,8,177,0.04519774011299435
2018-2-4,20,406,0.04926108374384237
2018-2-5,55,379,0.14511873350923482
2018-2-6,54,372,0.14516129032258066
2018-2-7,53,287,0.18466898954703834
2018-2-8,33,163,0.20245398773006135
2018-2-9,19,69,0.2753623188405797
2018-2-10,9,138,0.06521739130434782
2018-2-11,26,288,0.09027777777777778
2018-2-12,51,261,0.19540229885057472
2018-2-13,37,238,0.15546218487394958
2018-2-14,26,225,0.11555555555555555
2018-2-15,33,173,0.1907514450867052
2018-2-16,15,30,0.5
2018-2-17,4,70,0.05714285714285714
2018-2-18,7,217,0.03225806451612903
2018-2-19,37,270,0.13703703703703704
2018-2-20,34,269,0.12639405204460966
2018-2-21,45,215,0.20930232558139536
2018-2-22,30,150,0.2
2018-2-23,19,41,0.4634146341463415
2018-2-24,4,144,0.027777777777777776
2018-2-25,17,310,0.054838709677419356
2018-2-26,35,314,0.11146496815286625
2018-2-27,29,204,0.14215686274509803

**Comment by oliver-phet** [comment]
Using the stats MP provided in the last comment, we are at around 13% manual entries. In the last week since we added the exact match replace (https://github.com/phetsims/website-meteor/issues/54), we're at 11.52%.

We'll keep track of the percentage as we add more improvements https://github.com/phetsims/website-meteor/issues/55.

**Comment by mattpen** [comment]
@oliver-phet Here are the latest stats.  Some parts of the process were broken between late evening on 3/5 and midday on 3/6, so stats on those days may not reflect typical usage. 

Date,Schools Added,Users Added or Edited
2018-1-26,49,89,0.550561797752809
2018-1-27,15,223,0.06726457399103139
2018-1-28,33,407,0.08108108108108109
2018-1-29,51,412,0.12378640776699029
2018-1-30,61,408,0.14950980392156862
2018-1-31,63,378,0.16666666666666666
2018-2-1,52,239,0.2175732217573222
2018-2-2,35,90,0.3888888888888889
2018-2-3,8,177,0.04519774011299435
2018-2-4,20,406,0.04926108374384237
2018-2-5,55,379,0.14511873350923482
2018-2-6,54,372,0.14516129032258066
2018-2-7,53,287,0.18466898954703834
2018-2-8,33,163,0.20245398773006135
2018-2-9,19,69,0.2753623188405797
2018-2-10,9,138,0.06521739130434782
2018-2-11,26,288,0.09027777777777778
2018-2-12,51,261,0.19540229885057472
2018-2-13,37,238,0.15546218487394958
2018-2-14,26,225,0.11555555555555555
2018-2-15,33,173,0.1907514450867052
2018-2-16,15,30,0.5
2018-2-17,4,70,0.05714285714285714
2018-2-18,7,217,0.03225806451612903
2018-2-19,37,270,0.13703703703703704
2018-2-20,34,269,0.12639405204460966
2018-2-21,45,215,0.20930232558139536
2018-2-22,30,150,0.2
2018-2-23,19,41,0.4634146341463415
2018-2-24,4,144,0.027777777777777776
2018-2-25,17,310,0.054838709677419356
2018-2-26,35,314,0.11146496815286625
2018-2-27,29,259,0.11196911196911197
2018-2-28,18,234,0.07692307692307693
2018-3-1,23,130,0.17692307692307693
2018-3-2,17,63,0.2698412698412698
2018-3-3,6,121,0.049586776859504134
2018-3-4,15,220,0.06818181818181818
2018-3-5,25,191,0.13089005235602094
2018-3-6,4,202,0.019801980198019802
2018-3-7,14,227,0.06167400881057269

**Comment by mattpen** [comment]
@oliver-phet - Here are the statistics from the previous report up to the end of day yesterday:

2018-3-7,14,229,0.0611353711790393
2018-3-8,18,155,0.11612903225806452
2018-3-9,6,39,0.15384615384615385
2018-3-10,5,83,0.060240963855421686
2018-3-11,5,79,0.06329113924050633

**Comment by oliver-phet** [comment]
I recorded the numbers on user submitted schools in my latest batch:
Real School not in NCES database: 26
Duplicate in NCES: 37 (auto should have picked up: 3)
Bogus schools: 1

**Comment by mattpen** [comment]
@oliver-phet update for the past week:
2018-3-12,15,180,0.08333333333333333
2018-3-13,7,212,0.0330188679245283
2018-3-14,6,201,0.029850746268656716
2018-3-15,9,119,0.07563025210084033
2018-3-16,8,45,0.17777777777777778
2018-3-17,9,120,0.075
2018-3-18,8,69,0.11594202898550725

Total for these seven days was 6.5%

**Comment by mattpen** [comment]
2018-3-18,8,245,0.0326530612244898
2018-3-19,12,238,0.05042016806722689
2018-3-20,14,213,0.06572769953051644
2018-3-21,17,200,0.085
2018-3-22,13,246,0.052845528455284556
2018-3-23,12,204,0.058823529411764705
2018-3-24,16,195,0.08205128205128205
2018-3-25,9,423,0.02127659574468085
2018-3-26,24,212,0.11320754716981132
2018-3-27,22,145,0.15172413793103448
2018-3-28,11,111,0.0990990990990991

@oliver-phet here are the latest stats.

**Comment by mattpen** [comment]
Updated stats:

2018-3-29,4,80,0.05
2018-3-30,4,38,0.10526315789473684
2018-3-31,1,79,0.012658227848101266
2018-4-1,2,189,0.010582010582010581
2018-4-2,10,176,0.056818181818181816
2018-4-3,12,180,0.06666666666666667
2018-4-4,6,181,0.03314917127071823
2018-4-5,14,101,0.13861386138613863
2018-4-6,8,91,0.08791208791208792
2018-4-7,6,114,0.05263157894736842
2018-4-8,9,222,0.04054054054054054
2018-4-9,16,226,0.07079646017699115

**Comment by mattpen** [comment]
@oliver-phet - Do you want to continue tracking these or can we close this?

**Comment by oliver-phet** [comment]
Let's stop tracking for now. It looks like we are averaging around or under 5%. I'll keep this open until I confirm with KP.

**Comment by oliver-phet** [comment]
Closing.
