### ISSUE TITLE
International does not find IntL

### ISSUE THREAD

**Issue by BryceAG** [phetsims/website-meteor#61]
searching for "Armstrong G International" did not find Armstrong G Elem IntL Studies (chicago)

**Comment by mattpen** [comment]
@Oliver-phet is this a case we want to handle?

**Comment by oliver-phet** [comment]
Yes, there are a handful of schools that include 'intl'.

**Comment by lmulhall-phet** [comment]
Related to phetsims/QA/issues/104.

**Comment by mattpen** [comment]
@BryceAG @phet-steele - This should work now, please test and confirm.

![image](https://user-images.githubusercontent.com/11747676/36988717-c38fadf2-205c-11e8-8232-87d422a8d073.png)

**Comment by lmulhall-phet** [comment]
Fixed! Closing.
