### ISSUE TITLE
Martin L King Jr Elem Sch (school isn't working)

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/website-meteor#62]
- I was trying to find "Martin L King Jr Elem Sch."
- It seems like school vs. sch is the issue.
- For some reason, al or AL isn't working in the search.
- I will investigate more on Monday.

Related to phetsims/QA/issues/104.

![screen shot 2018-03-02 at 4 15 54 pm](https://user-images.githubusercontent.com/31285590/36926900-6dcd1732-1e37-11e8-8415-23e4fa561b7a.png)

EDIT:
- "martin l king jr elem school al" yields no suggestions
- "martin king junior elementary school alabama" no sug.
- "martin king junior elementary school tuscaloosa alabama" no sug.
- "martin l king junior elementary sch al" yields correct suggestion.

**Comment by mattpen** [comment]
@lmulhall-phet @phet-steele - I have implemented a fix that allows all of the above searches to find that school.  Please test and confirm.

![image](https://user-images.githubusercontent.com/11747676/36988566-697def4a-205c-11e8-8503-d9f549f8c3f1.png)
![image](https://user-images.githubusercontent.com/11747676/36988590-78f940be-205c-11e8-8015-f5317ec02cdd.png)
![image](https://user-images.githubusercontent.com/11747676/36988606-831fcac2-205c-11e8-81fd-4fd72cc0fa3c.png)
![image](https://user-images.githubusercontent.com/11747676/36988622-8d71b77e-205c-11e8-8a1a-0f5b7e0ce7a8.png)

**Comment by lmulhall-phet** [comment]
Fixed! Closing.
