### ISSUE TITLE
academy does not find acad

### ISSUE THREAD

**Issue by BryceAG** [phetsims/website-meteor#63]
"Sheridan Elem Math & Science Academy" does not find "Sheridan Elem Math & Science Acad"
... while I'm at it "Seward Elem Communication Arts Academy" doesn't find "Seward Elem Communication Arts Ac" but I don't think "Ac" is often used enough to be an issue

**Comment by lmulhall-phet** [comment]
Related to phetsims/QA/issues/104.

**Comment by mattpen** [comment]
@BryceAG @phet-steele - I've implemented a fix for 'acad', but not for 'ac'.  Please test and confirm.

![image](https://user-images.githubusercontent.com/11747676/36988781-f0a43240-205c-11e8-8889-b230d5b59e0b.png)

**Comment by lmulhall-phet** [comment]
Fixed! Closing.
