### ISSUE TITLE
"Center" needs to find CNTR

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#64]
@mattpen it already finds "CTR", but we also need to find "CNTR". For #55.

**Comment by mattpen** [comment]
@phet-steele - I've implemented a fix for "cntr", but we are not handling "ctr" that I am aware of.  Can you please provide an example of a search that matches "ctr" with the term "center"?

**Comment by phet-steele** [comment]
> I've implemented a fix for "cntr", but we are not handling "ctr" that I am aware of.

I was looking at https://github.com/phetsims/website-meteor/issues/55#issuecomment-368694525, but you are correct, looks like that isn't working. I think I interpreted that comment wrong, the string on the left must be searches, not results?

**Comment by phet-steele** [comment]
"CNTR" is working:

<img width="629" alt="screen shot 2018-03-05 at 10 34 01 am" src="https://user-images.githubusercontent.com/5863899/36990088-c99a4e92-2060-11e8-9c81-eeebdf999e9d.png">

And correct, "CTR" is not being handled yet:
<img width="637" alt="screen shot 2018-03-05 at 10 35 56 am" src="https://user-images.githubusercontent.com/5863899/36990178-0983fee0-2061-11e8-8abf-438abfecaab3.png">
<img width="558" alt="screen shot 2018-03-05 at 10 36 02 am" src="https://user-images.githubusercontent.com/5863899/36990179-0998a4a8-2061-11e8-8d1c-c63b8878b711.png">

**Comment by mattpen** [comment]
This was updated and deployed to production.
