### ISSUE TITLE
"Learning" needs to find "LRNG"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/website-meteor#65]
@mattpen, for #55.

**Comment by mattpen** [comment]
@phet-steele Fix has been implemented, please test and confirm.

**Comment by phet-steele** [comment]
@mattpen turns out there are also "LRN" and "LRNING" terms to find. "LRNG" is working:

<img width="661" alt="screen shot 2018-03-05 at 10 31 02 am" src="https://user-images.githubusercontent.com/5863899/36989950-66daf856-2060-11e8-8938-560beb116056.png">

**Comment by mattpen** [comment]
This was updated and deployed to production.
