### ISSUE TITLE
Science does not find sci

### ISSUE THREAD

**Issue by BryceAG** [phetsims/website-meteor#66]
"Shoop Math-Science Tech Elem Academy" does not find "Shoop Math-Sci Tech Elem Academy"

although fortunately "math sci" without the hyphen does work

**Comment by mattpen** [comment]
@BryceAG @phet-steele - I've implemented a fix, please test and confirm.

![image](https://user-images.githubusercontent.com/11747676/36988975-8be031f0-205d-11e8-8280-c53a4a9338a1.png)

**Comment by lmulhall-phet** [comment]
Fixed! Closing.
