### ISSUE TITLE
Ignore punctuation when checking for duplicate school

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#68]
Matt Pennington [5:01 PM]
Yes, it looks like we aren't removing punctuation in the duplicate check.
Oliver Nix [5:01 PM]
can you add that?
Matt Pennington [5:03 PM]
Sure, can you open an issue in website-meteor please?

**Comment by mattpen** [comment]
@oliver-phet - I've deployed a solution to ox-dev, you can test it out by editing your profile at https://ox-dev.colorado.edu.

To check names now, we are checking a name match by removing any punctuation from this list `.-_,/\[]{}()+=?'";:<>*!@#$%^&` in both the name in the database and the name provided by the user.  This is working now for the example you provided in slack and a few others I tested ( ST. FRANCIS DE SALES SCHOOL in Houston ).

**Comment by mattpen** [comment]
@oliver-phet - Can you please review?  Do you think we should run a QA test?

**Comment by oliver-phet** [comment]
I just edited my school to "ALEGENT IMMANUEL RTC" Omaha, NE. This school was not auto replaced to "ALEGENT/IMMANUEL RTC" (in NCES). Is the 'space' causing this?

**Comment by oliver-phet** [comment]
I just tried "ALEGENTIMMANUEL RTC" and it also wasn't auto replaced?

**Comment by oliver-phet** [comment]
<img width="1573" alt="image" src="https://user-images.githubusercontent.com/5090275/40320086-a5eedefe-5ce7-11e8-9b23-8ba8e7dec98c.png">

**Comment by mattpen** [comment]
@oliver-phet - If we include spaces in the "punctuation" to be removed when checking duplicates, there is a much higher chance of false duplicate detection.  I can add it, but is this risk acceptable?

**Comment by oliver-phet** [comment]
No, I don't want to try to handle spaces.

I'm confused as to why "ALEGENTIMMANUEL RTC" was not auto-replaced, though. 
> To check names now, we are checking a name match by removing any punctuation from this list .-_,/\[]{}()+=?'";:<>*!@#$%^& in both the name in the database and the name provided by the user. 

If the "/" was removed on the database side, I would expect it to auto-replace.

**Comment by mattpen** [comment]
@oliver-phet - both Alegent Immanuel cases and the "ST. FRANCIS DE SALES SCHOOL" case should be working now on ox-dev.  Can you please review?

**Comment by oliver-phet** [comment]
Looks good. I tested by entering "HORIZONS K8 SCHOOL" (there is an NCES entry 'HORIZONS K-8 SCHOOL') and the school was auto-replaced.

**Comment by mattpen** [comment]
This was deployed to production.
