### ISSUE TITLE
Add 'Include schools awaiting validation' checkbox to top of admin/schools

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#69]
The only way I can get a list of schools awaiting validation is to show all schools in the US that aren't NCES and that list is getting quite long.

This could be added the same way for Orgs 'Include organizations awaiting validation'.

**Comment by mattpen** [comment]
@oliver-phet - Do you mean an "Only include schools awaiting validation" checkbox?  Currently the search includes these schools.

**Comment by oliver-phet** [comment]
I need a checkbox that _only_ includes schools awaiting validation (in the country and state entered in the comboboxes above).

**Comment by oliver-phet** [comment]
So the search would not include NCES or validated schools. The button does something similar to this, but includes all countries.

**Comment by mattpen** [comment]
Should I remove the button?  It seems largely useless if we add this filter to the search.

**Comment by mattpen** [comment]
@oliver-phet - I've deployed a potential solution to ox-dev, can you please test?

**Comment by oliver-phet** [comment]
This looks fine. I can't really test on ox-dev because there are so few awaiting validation. Can you deploy and keep this open?

**Comment by mattpen** [comment]
Sure, it will be deployed whenever #68 is ready.

**Comment by oliver-phet** [comment]
It sounds like we are going to remove the button and add two checkboxes:
- Include Pending
- Include Validated

**Comment by mattpen** [comment]
@oliver-phet - These filters are working now on ox-dev.  I'll deploy them to production tonight.

**Comment by mattpen** [comment]
This was deployed to production.
