### ISSUE TITLE
Implement mobile layout for the registration page

### ISSUE THREAD

**Issue by mattpen** [phetsims/website-meteor#7]
We need to add css media query breakpoints and style rules for the mobile layout.  This could be delayed until after publication by adding a minimum width to the page.

**Comment by mattpen** [comment]
@oliver-phet - Aside from the footer, the mobile layout for the registration page should be ready to go.  Can you please review it?  I'll make sure to put up the production version on ox-dev so you can access it.

**Comment by oliver-phet** [comment]
Add some space between 'student' buttons on mobile. Looks fine on desktop.
![image](https://user-images.githubusercontent.com/5090275/31906592-b5dbf0a2-b7ee-11e7-9f2c-1dfcb61cc113.png)

**Comment by oliver-phet** [comment]
Also, not sure if it will be linked in the future, but the text "By clicking register, you agree to the University of Colorado's privacy policy" isn't linked to the privacy policy (like on production) http://www.cu.edu/privacy-policy.

The font can also be made smaller (11pt) in mockup.

**Comment by oliver-phet** [comment]
We'll hopefully discuss footer this week, so hopefully this won't be an issue... but the sponsor logos are cutoff right now.
![image](https://user-images.githubusercontent.com/5090275/31908104-11945246-b7f3-11e7-856d-01c1befaa30a.png)

**Comment by mattpen** [comment]
@oliver-phet - These changes have been implemented.  Can you check once more and see if anything else needs fixed on the registration page?

**Comment by oliver-phet** [comment]
Can you modify the privacy policy link to open in a new tab? I clicked it on mobile and after going 'back' it restarted my registration progress.

**Comment by mattpen** [comment]
@oliver-phet - I made that change and pushed it to ox-dev.

**Comment by mattpen** [comment]
@oliver-phet - any other changes to make for this issue, or can it be closed?

**Comment by oliver-phet** [comment]
Looks good. Closing.
