### ISSUE TITLE
Auto-validate International schools and Organizations

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#70]
@mattpen KP and I discussed and we would like to auto-validate International schools and all Organizations (US and International). We need to use the same auto-replace rules that are already instrumented to US schools.

Also, can you validate all international schools and organizations awaiting validation?

**Comment by mattpen** [comment]
All organizations have now been validated as well.

**Comment by mattpen** [comment]
The auto validation was deployed to production tonight.
