### ISSUE TITLE
Show country in result list

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#71]
@mattpen Can we add the country in the results list for schools and orgs?
Something like this ("United States" added):
![image](https://user-images.githubusercontent.com/5090275/40555937-fcc7af3a-6007-11e8-860a-6cf3700d4aaf.png)

**Comment by mattpen** [comment]
@oliver-phet - I've deployed this change to ox-dev.  It seems to be working fine so I'll deploy it along with the fixes for #72 and #73

**Comment by mattpen** [comment]
This was deployed tonight.
