### ISSUE TITLE
Prioritize Country and State in results

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#72]
Not sure how possible this is, but could a users (home) country and state be used to sort the results? i.e. If I enter United States/Colorado as my country/state, then the list of results would rank Colorado schools first, then US schools, then International schools?

**Comment by mattpen** [comment]
@oliver-phet  - Would this be a higher priority than exact or substring matches on the name?

**Comment by oliver-phet** [comment]
Exact matches should be first. But if a user types "washington high school" (there are ~8 of these in NCES), it would rank:
1. schools in user's state
2. schools in user's country
3. other schools

I'm not sure how this should work in combination with substring matches. Do you have an example of that?

**Comment by mattpen** [comment]
We need to decide on a priority for the various means of ranking.  Based on your description I think the final sort order would be:

1. The search string is an exact match of the name
2. There is an exact match of the user's home state and country
3. There is an exact match of the user's home country
4. The search string is a substring of the name or vice versa
5. Alphabetical precedence

**Comment by oliver-phet** [comment]
I think we would want it expanded?

1. The search string is an exact match of the name
2. There is an exact match of the user's home state and country
3. There is an exact match of the user's home country
4. There is a substring match in the user's home state and country
5. There is a substring match in the user's and country
6. Alphabetical precedence

**Comment by mattpen** [comment]
> There is a substring match in the user's home state and country

I'm not sure I'm following on this one.  Also you left out the substring matches on the name (the current priority sort behavior), was this intentional?

**Comment by oliver-phet** [comment]
@mattpen and I zoomed and the order he listed in https://github.com/phetsims/website-meteor/issues/72#issuecomment-392971156 is the order we'll go with.

**Comment by mattpen** [comment]
This was deployed to production tonight.
