### ISSUE TITLE
Add 'Homeschool' entry to schools

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/website-meteor#73]
Can we add a custom 'Homeschool' entry to the schools database? This would need to be a school that isn't tagged to a country or state (otherwise I would manually add it). 

Then, all users can select this as an option if they homeschool (and we avoid have a lot of custom homeschool entries from various users).

**Comment by mattpen** [comment]
@oliver-phet - Is there any text we can add to the district or location?  With just the name field the item doesn't really stand out from the item below it.  Maybe a `state` of "Anywhere" or "Any organization"?

![image](https://user-images.githubusercontent.com/11747676/40664630-99e176d0-6318-11e8-9f33-b89b3939cea5.png)

**Comment by mattpen** [comment]
I've added Homeschool to the production db.  The improvements to sort will be deployed along with #72.

**Comment by oliver-phet** [comment]
@mattpen I'm not seeing this on edit profile or register? (And we continue to get users registering under city-specific homeschool)
![image](https://user-images.githubusercontent.com/5090275/45062058-8044a280-b064-11e8-89cb-434eca50bc9d.png)

**Comment by mattpen** [comment]
@oliver-phet - It looks like there was a typo when I added the homeschool entry.  The keyword was spelled `homeshcool`.  I fixed this and it is now showing up correctly:

![image](https://user-images.githubusercontent.com/11747676/45123534-7edaaf00-b124-11e8-8187-bcaddf3b461e.png)
