### ISSUE TITLE
Footer appears at the top of the page on load/reload

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/website-meteor#76]
For https://github.com/phetsims/QA/issues/359, though it mat impact other pages.  Recorded on Win 10 chrome.
When loading or reloading the page, the footer of the page appears at the top, with things like the text or the image carousel appearing bellow it.
From slack:
>I've noticed that too. I thought I had fixed it, but apparently not.  Please open an issue.

So this may be a regression of some sort.

**Comment by KatieWoe** [comment]
![refreshattop](https://user-images.githubusercontent.com/41024075/60847371-b0d2fc80-a19f-11e9-805d-85a3ddc31707.gif)

**Comment by chrisklus** [comment]
@mattpen this technically still happens for a hot second (while throttling the page, repeatedly scroll down until the footer appears with the front page below it)... but I think our loading screen fixes the visibility of the problem, so I'm happy to close if you are.

**Comment by mattpen** [comment]
> I'm happy to close if you are.

+1
