### ISSUE TITLE
Subject icon wiggles on hover

### ISSUE THREAD

**Issue by chrisklus** [phetsims/website-meteor#79]
At some window widths, the subject icons wiggle by one pixel when the circle is being hovered. Since they are just centered with `margin: auto`, this is likely happening because of some small division error.

![Kapture 2019-08-16 at 20 33 08](https://user-images.githubusercontent.com/5618316/63204486-20bd8800-c066-11e9-9bac-0315fb12eaa3.gif)

There is no way to fix this with my current implementation, so @mattpen suggested a very nice idea of moving the background styling to a pseudo element.

**Comment by chrisklus** [comment]
The refactor appears to be working, and I'm no longer able to get the icons to wiggle. Ready for QA to test - please quickly test the hover behavior of any of the circles for a wide range of browser window widths.

**Comment by KatieWoe** [comment]
Wasn't able to replicate on a variety of browsers and window sizes.  Will reopen if it shows up again.
